# Setup file for readthedocs

# Build PDF & ePub
formats:
    - epub
    - pdf

# library requirements
requirements_file: requirements_rtd.txt

# python version
python:
   version: 3

# how to install library
python:
   setup_py_install: true
